---
name: pvcast
version: 0.0.1
slug: pvcast
description: pvcast - local solar forecasting
url: https://github.com/Open-HEMS/pvcast-addon
init: false
hassio_api: true
map: ['addon_config']
arch:
  - aarch64
  - amd64
  - armv7
options:
  workers: 1
  test_option: false
  sources:
    - name: HomeAssistant
      type: homeassistant
    - name: ClearOutside
      type: clearoutside
schema:
  workers: int(1,4)
  test_option: bool
  sources:
    - name: str
      type: str
